/**
 * Shopping Cart Tests
 *
 * TODO: Use Claude Code to generate comprehensive tests
 * based on your requirements in tdd-strategy.md
 *
 * Run: npm test
 */

import { describe, it, expect, beforeEach } from "vitest";
import {
  addItem,
  removeItem,
  updateQuantity,
  applyPromoCode,
  calculateTotals,
  clearCart,
  getCart,
} from "./shopping-cart.js";

// =============================================================================
// Setup
// =============================================================================

beforeEach(() => {
  clearCart();
});

// =============================================================================
// Sample Tests (Students should generate more with Claude)
// =============================================================================

describe("Shopping Cart", () => {
  describe("Add Item", () => {
    it("should add a valid product to cart", () => {
      const result = addItem("PROD-001", 1);

      expect(result.success).toBe(true);
      expect(result.cart).toHaveLength(1);
      expect(result.cart![0].productId).toBe("PROD-001");
    });

    it("should reject invalid product ID", () => {
      const result = addItem("INVALID-ID", 1);

      expect(result.success).toBe(false);
      expect(result.error).toContain("not found");
    });

    // TODO: Generate more tests with Claude for:
    // - Adding same product twice (quantity should increase)
    // - Invalid quantities (negative, zero)
    // - Inventory validation
  });

  describe("Calculate Totals", () => {
    it("should calculate subtotal correctly", () => {
      addItem("PROD-001", 2); // 29.99 * 2 = 59.98

      const totals = calculateTotals();

      expect(totals.subtotal).toBeCloseTo(59.98, 2);
    });

    // TODO: Generate more tests with Claude for:
    // - Tax calculation
    // - Discount application
    // - Shipping calculation
    // - Rounding edge cases
  });
});

// =============================================================================
// YOUR AI-GENERATED TESTS GO BELOW
// =============================================================================

// TODO: Paste tests generated by Claude Code here
// Use the prompt from the README to generate comprehensive tests
